// automatically generated by the FlatBuffers compiler, do not modify

package com.example.hellojni.ReposNormal;

import com.google.gson.*;

import java.util.ArrayList;

@SuppressWarnings("unused")
public final class ReposList{
  ArrayList<Repo> repos;

  public ReposList fromJson(String jsonString) {
    JsonObject jsonObj = (new JsonParser().parse(jsonString)).getAsJsonObject();
    JsonArray repoArray = jsonObj.get("repos").getAsJsonArray();
    repos = new ArrayList<>();
    for(JsonElement repoObj : repoArray) {
      repos.add(new Repo().fromJson(repoObj.getAsJsonObject().toString()));
    }
    return this;
  }
}

